config_name: hyper-Unet_mri
description: "hyper-Unet for MRI Reconstruction"

device_params:
  visible_devices: "1, 2, 3" # [0,1,2], [0]
  device_id: 1

model_params:
  T: 1000
  in_channels: 2
  out_channels: 2
  ch: 64
  ch_mult: [1, 2, 2, 2]
  attn: []
  num_res_blocks: 2
  dropout: 0.0
  ph_n: 2

dataset_params:
  dataset_name: fMRI_dataset
  dataset_path: '/media/NAS06/haosen/knee_path/multicoil_dataset/knee_dataset_x8.h5'
#  dataset_path: 'datasets/fastmri/knee_dataset.h5'
  mask: "fMRI_Reg_AF8_CF0.04_PE320"
  sigma: 0.01
  val_data: True
  batch_size: 8

train_params:
  epochs: 50
  model_name: hyperUnet

  restore_weights: False #False, best, inter, final
  restore_path:

  loss_name: MSE
  score_names: ['PSNR', 'SSIM']
  optim_name: Adam
  optim_params:
    lr: 0.001
    weight_decay: 1e-5
  gradient_clip: True

  scheduler_name: ReduceLROnPlateau
  scheduler_params:
    mode: max
    factor: 0.5
    patience: 10
    min_lr: 1e-6
    verbose: True