config_name: unet_mri
description: "UNet for MRI Reconstruction"

device_params:
  visible_devices: "1, 2, 3" # [0,1,2], [0]
  device_id: 1

model_params:
  ph_n: 2
  in_channels: 2
  model_channels: 64
  out_channels: 2
  num_res_blocks: 2
  attention_resolutions: []
  dropout: 0.1
  channel_mult: [1, 2, 2, 2]
  conv_resample: True
  dims: 2
  num_heads: 1
  num_heads_upsample: 1
  use_scale_shift_norm: True
  use_checkpoint: True

dataset_params:
  dataset_name: fMRI_dataset
#  dataset_path: '/media/NAS06/haosen/knee_path/multicoil_dataset/knee_dataset_x8.h5'
  dataset_path: 'datasets/fastmri/knee_dataset.h5'
  mask: "fMRI_Reg_AF8_CF0.04_PE320"
  sigma: 0.01
  val_data: True
  batch_size: 25

train_params:
  epochs: 50
  model_name: unet

  restore_weights: False #False, best, inter, final
  restore_path:

  loss_name: MSE
  score_names: ['PSNR', 'SSIM']
  optim_name: Adam
  optim_params:
    lr: 0.001
    weight_decay: 1e-5
  gradient_clip: True

  scheduler_name: ReduceLROnPlateau
  scheduler_params:
    mode: max
    factor: 0.5
    patience: 10
    min_lr: 1e-6
    verbose: True